config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root :to => 'welcome#index'
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy]
    resources :comments, only: [:destroy]
    post "/posts/:id/like" => "posts#like", as: :like
    post "/posts/:id/comment" => "posts#comment", as: :comments
    end
  
  namespace :api do
    namespace :v1 do
      devise_for :users, :skip => [:registrations, :passwords, :confirmations ]
      resources :posts, only: [:index]
    resources :comments, only: [:index, :create]
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all

    if user.admin? :admin
      can :manage, :all
    else
      can :manage, Comment, user_id: user.id
      can :manage, Post, user_id: user.id
      can :read, :all
      can :add, Comment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_destroy :delete_comments_counter
  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def delete_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_destroy :delete_posts_counter
  after_save :update_posts_counter

  def update_posts_counter
    user.increment!(:postscounter)
  end

  def delete_posts_counter
    user.decrement!(:postscounter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes
  validates :name, presence: true
  validates :postscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end

  def admin?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      def index
        @comments = Comment.order('created_at DESC')
        render json: {
          success: true, message: 'Successfully loaded comments', data: { comments: @comments }
        }
      end

      def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params, user_id: params[:user_id])

        if @comment.save
          render json: { success: true, message: 'Successfully created comment', data: { comment: @comment } },
                 status: :created
        else
          render json: { success: false, errors: @comment.errors }, status: :unprocessable_entity
        end
      end
    rescue ActiveRecord::RecordNotFound
      no_record(params[:post_id])
    end

    private

    def no_record(post)
      render json: { success: false, message: "This post: #{post} does not exist" }, status: :not_found
    end

    def comment_params
      params.require(:comment).permit(:text)
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        @posts = Post.order('created_at DESC')
        render json: { success: true, message: 'Successfully loaded all posts', data: { posts: @posts } }, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :posts_counter, :email, :password, :password_confirmable)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find_by(id: @comment.post_id)
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to user_posts_path(current_user, @post.id), notice: 'Comment was successfully deleted.' }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: params[:id]).where(author_id: params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.comments_counter
    @post.likes_counter

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_path(current_user, @post), notice: 'Post was successfully created.' }
      end
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def like
    @post = Post.find(params[:id])
    Like.new(user: current_user, post: @post).save
    redirect_to user_posts_path(current_user)
  end

  def comment
    @post = Post.find(params[:id])
    p params
    @comment = Comment.new(user: current_user, post: @post, text: params[:text])
    @comment.save
    authorize! :create, @comment
    redirect_to user_posts_path(current_user)
  end

  def destroy
    @post = Post.find(params[:id])
    @comment = @post.comments.where(post_id: @post.id)
    @like = @post.likes.where(post_id: @post.id)
    @comment.each(&:destroy)
    @like.each(&:destroy)
    @post.destroy

    respond_to do |format|
      format.html { redirect_to user_posts_path, notice: 'Post was successfully removed.' }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
  <hr>
  <% if comments.any? %>
    <% comments.includes(:user).each do |comment| %>
      <div>
        <div>
          <p>
            <b><%= comment.user.name %></b>
          </p>
          <p class="comment">
            <%= comment.text %>
          </p>
        </div>
      </div>
          <% if can? :destroy, comment %>
        <%= button_to "Delete", user_comment_path(comment.post_id, comment), method: :delete %>
    <% end %>
    <% end %>
  <% else %>
    <p class="comment">No comments to display.</p>
  <% end %>
</div>

app/views/comments/_new.html.erb
<div class="callout large banner">
  <div class="grid-x grid-padding-x">
    <%= link_to "< Back", user_post_path(@comment.user_id, @comment.post_id), class: "cell small-4" %>
    <div class="cell small-4 text-center">New Comment</div>
    <div class="cell small-4 text-right"></div>
  </div>
</div>

<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x flex-container flex-dir-column">
        <div class="medium-12 cell">
            <p class="text-lg">Comment:</p>
            <%= form.text_area :text, placeholder: "Write Comment", rows: "8", required: true %>
        </div>
        <div class="medium-12 cell text-center">
            <%= form.submit "Submit Comment", class: 'button' %>
        </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div>
  <h4><%= link_to post.title, user_post_path(post.user_id, post) %></h4>
  <p><%= post.text %></p>
  <ul>
      <li>Comments: <%= post.comments_counter%></li>
      <li>Likes: <%= post.likes_counter%></li>
  </ul>
  
   <% if can? :destroy, post %>
      <%= button_to "Delete", user_post_path(post.user_id, post), method: :delete %>
    <% end %>
 
    <%= render partial: "comments/comment", locals: { comments: post.recent_comments } %>
</div>

app/views/posts/_post_info.html.erb
<div class="callout post">
    <div class="flex-container align-justify">
        <div>
            <h4><%= post.title %></h4>
            <p>by <%= post.user_id %></p>
        </div>
        <ul class="menu simple align-right">
            <li>Comments: <%= post.comments_counter%></li>
            <li>Likes: <%= post.likes_counter%></li>
        </ul>
    </div>
    <p><%= post.text %></p>

        <ul class="menu simple add align-right">
        <li>
            <%=form_with :url => user_comments_path(@post.user_id, @post), :method => :post, :class => 'new-comment' do |f|%>
      <%=f.text_field :text, placeholder: 'Comment', class: 'comment-text'%>
      <%=f.submit 'Comment', class: 'comment-submit'%>
    <%end%>
        </li>
        <li>
            <%= button_to user_like_path(@post.user_id, @post), method: :post do %>
                <span>Like</span>
            <% end %>
        </li>
    </ul>
    <%= render partial: "comments/comment", locals: { comments: post.comments } %>
</div>

app/views/posts/index.html.erb
<h1>Here is a list of all posts by a user</h1>

<div class="user">
  <div class="user--avatar">
    <%=image_tag("https://robohash.org/#{@user.id}.png", class: 'user--avatar', alt: 'user picture')%>
  </div>
  <div class="user--name">
    <%=link_to @user.name, user_path(@user), class: 'name'%>
    <%=link_to "Number of posts: #{@user.postscounter}",          user_posts_path(@user), class: 'posts-num'%>
  </div>
</div>

<div class="blog-post">
  <% @posts.reverse_each do |post| %>
    <%= render partial: "post", locals:{ post: post } %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<%= form_with model: @post, url: user_posts_path do |form| %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x flex-container flex-dir-column">
        <div class="medium-8 cell">
            <p class="text-lg">Title:</p>
            <%= form.text_field :title, placeholder: "Post title", required: true %>
        </div>
        <div class="medium-12 cell">
            <p class="text-lg">Text:</p>
            <%= form.text_area :text, placeholder: "Write post", rows: "8", required: true %>
        </div>
        <div class="medium-12 cell text-center">
            <%= form.submit "Submit Post", class: 'button' %>
        </div>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Here is a post by username</h1>

<div class="callout large banner">
  <div class="grid-x grid-padding-x">
    <%= render 'layouts/alerts' if notice %>
  </div>
</div>

<%= render partial: "post_info", locals: { post: @post } %>

app/views/users/index.html.erb
<h1>Here is a list of all users</h1>
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>

<div class="user-list">
  <% @users.each do |user| %>
    <div class="user">
      <div class="user--avatar">
        <%=image_tag("http://identicon.net//#{user.id}.png", class: 'user--avatar', alt: 'user picture')%>
      </div>
      <div class="user--name">
        <%=link_to user.name, user_path(user), class: 'name'%>
        <%=link_to "Number of posts: #{user.postscounter}",          user_posts_path(user), class: 'posts-num'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Here is a user</h1>
<div class="user">
  <div class="user--avatar">
    <%=image_tag("https://robohash.org/#{@user.id}.png", class: 'user--avatar', alt: 'user picture')%>
  </div>
  <div class="user--name">
    <%=link_to @user.name, user_path(@user), class: 'name'%>
    <%=link_to "Number of posts: #{@user.postscounter}",          user_posts_path(@user), class: 'posts-num'%>
  </div>
</div>
<div class="user--bio">
  <h3>Bio</h3>
  <p><%= @user.bio %></p>
</div>
<%@user.recent_posts.each.with_index(1) do |post, idx|%>
  <div class="user--post">
    <h3><%=link_to post.title, user_post_path(@user, post) %></h3>
    <p><%= post.text.slice(0...50) + '...' %></p>
    <p class='count'>Comments <%=post.comments_counter%>, Likes <%=post.likes_counter%></p>
  </div>
<%end%>
<div class="cell small-4 text-right">
    <% if @user == current_user %>
      <%= link_to new_user_post_path(@user) do %>
          <span>New Post</span>
      <% end %>
    <% end %>
    </div>
<div class="btn">
  <%=link_to "See all posts", user_posts_path(@user), class: 'show-posts'%>
</div>

app/views/welcome/index.html.erb
<nav class="top-bar margin-bottom-3" data-topbar>
  <div>
    <ul>
      <li>
        <%= link_to "My Blog", root_path %>
      </li>
    </ul>
  </div>
  <div>
    <ul>
      <li>
        <%= link_to "Blogs by Users", users_path %>
        
      </li>
      <% if user_signed_in? %>
        <li>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= button_to "Login", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>